// Package tts provides text-to-speech functionality for the companion app.
// It supports Kokoro-FastAPI as the backend TTS service.
package tts

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"time"
)

// Service defines the interface for text-to-speech operations.
type Service interface {
	// Synthesize converts text to speech and returns the complete audio bytes.
	Synthesize(ctx context.Context, text string, voice string) ([]byte, error)

	// SynthesizeStream converts text to speech and returns a streaming reader.
	// The caller must close the returned ReadCloser when done.
	SynthesizeStream(ctx context.Context, text string, voice string) (io.ReadCloser, error)
}

// KokoroClient is a client for the Kokoro-FastAPI HTTP API.
type KokoroClient struct {
	endpoint     string
	client       *http.Client // used for Synthesize (with timeout)
	streamClient *http.Client // used for SynthesizeStream (no timeout; ctx controls deadline)
	log          *slog.Logger
}

// KokoroOptions configures the Kokoro client.
type KokoroOptions struct {
	Endpoint string
	Timeout  time.Duration
}

// NewKokoroClient creates a new Kokoro-FastAPI HTTP client.
func NewKokoroClient(log *slog.Logger, opts KokoroOptions) *KokoroClient {
	timeout := opts.Timeout
	if timeout == 0 {
		timeout = 30 * time.Second
	}
	endpoint := opts.Endpoint
	if endpoint == "" {
		endpoint = "http://memoh-kokoro-tts:8880"
	}
	return &KokoroClient{
		endpoint:     endpoint,
		client:       &http.Client{Timeout: timeout},
		streamClient: &http.Client{}, // no timeout; caller passes ctx with deadline
		log:          log.With(slog.String("component", "kokoro-tts")),
	}
}

// speechRequest represents the request body for Kokoro TTS API.
type speechRequest struct {
	Model          string  `json:"model"`
	Input          string  `json:"input"`
	Voice          string  `json:"voice"`
	ResponseFormat string  `json:"response_format"`
	Speed          float64 `json:"speed"`
	Stream         bool    `json:"stream,omitempty"`
}

// Synthesize converts text to speech using Kokoro-FastAPI.
// Returns the complete audio bytes once synthesis is done.
func (c *KokoroClient) Synthesize(ctx context.Context, text string, voice string) ([]byte, error) {
	if text == "" {
		return nil, fmt.Errorf("tts: empty text")
	}
	if voice == "" {
		voice = "af_bella"
	}

	body, err := c.buildRequest(text, voice, false)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodPost, c.endpoint+"/v1/audio/speech", body)
	if err != nil {
		return nil, fmt.Errorf("tts: failed to create request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")

	c.log.Debug("TTS request", slog.String("text", text), slog.String("voice", voice))

	resp, err := c.client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("tts: request failed: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		b, _ := io.ReadAll(resp.Body)
		return nil, fmt.Errorf("tts: unexpected status %d: %s", resp.StatusCode, string(b))
	}

	audio, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("tts: failed to read response: %w", err)
	}
	c.log.Debug("TTS done", slog.Int("audio_bytes", len(audio)))
	return audio, nil
}

// SynthesizeStream converts text to speech and returns a streaming reader.
// Audio bytes are returned as they are generated by Kokoro.
// The caller MUST close the returned ReadCloser.
func (c *KokoroClient) SynthesizeStream(ctx context.Context, text string, voice string) (io.ReadCloser, error) {
	if text == "" {
		return nil, fmt.Errorf("tts: empty text")
	}
	if voice == "" {
		voice = "af_bella"
	}

	body, err := c.buildRequest(text, voice, true)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodPost, c.endpoint+"/v1/audio/speech", body)
	if err != nil {
		return nil, fmt.Errorf("tts: failed to create stream request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")

	c.log.Debug("TTS stream request", slog.String("text", text), slog.String("voice", voice))

	resp, err := c.streamClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("tts: stream request failed: %w", err)
	}
	if resp.StatusCode != http.StatusOK {
		b, _ := io.ReadAll(resp.Body)
		resp.Body.Close()
		return nil, fmt.Errorf("tts: stream unexpected status %d: %s", resp.StatusCode, string(b))
	}
	// Return the body directly; caller reads and closes it.
	return resp.Body, nil
}

func (c *KokoroClient) buildRequest(text, voice string, stream bool) (*bytes.Reader, error) {
	r := speechRequest{
		Model:          "kokoro",
		Input:          text,
		Voice:          voice,
		ResponseFormat: "wav",
		Speed:          1.0,
		Stream:         stream,
	}
	b, err := json.Marshal(r)
	if err != nil {
		return nil, fmt.Errorf("tts: marshal request: %w", err)
	}
	return bytes.NewReader(b), nil
}

// NoOpClient is a no-op TTS client used when TTS is not configured.
type NoOpClient struct{}

func (n *NoOpClient) Synthesize(_ context.Context, _ string, _ string) ([]byte, error) {
	return nil, fmt.Errorf("tts: service not configured")
}

func (n *NoOpClient) SynthesizeStream(_ context.Context, _ string, _ string) (io.ReadCloser, error) {
	return nil, fmt.Errorf("tts: service not configured")
}

// SentenceSplitter splits streaming text into sentences for TTS triggering.
// It looks for sentence-ending punctuation: . ! ? 。！？\n
//
// Sentences shorter than minLen runes are held in the buffer and merged
// with the next sentence to avoid triggering TTS for isolated punctuation.
type SentenceSplitter struct {
	buffer string
}

const minTTSSentenceLen = 5 // minimum rune count to trigger TTS

// NewSentenceSplitter creates a new sentence splitter.
func NewSentenceSplitter() *SentenceSplitter {
	return &SentenceSplitter{}
}

// AddText adds text to the buffer and returns any complete sentences
// that are long enough to synthesize.
func (s *SentenceSplitter) AddText(text string) []string {
	s.buffer += text
	return s.extractSentences()
}

// Flush returns any remaining text in the buffer (non-empty and not blank).
func (s *SentenceSplitter) Flush() string {
	result := s.buffer
	s.buffer = ""
	if len([]rune(result)) < minTTSSentenceLen {
		return ""
	}
	return result
}

// extractSentences extracts complete sentences from the buffer.
// Sentences with fewer than minTTSSentenceLen runes are kept in the buffer
// and merged with subsequent text.
func (s *SentenceSplitter) extractSentences() []string {
	var sentences []string
	start := 0

	for i, r := range s.buffer {
		if isSentenceEnd(r) {
			end := i + len(string(r))
			sentence := s.buffer[start:end]
			if len([]rune(sentence)) >= minTTSSentenceLen {
				sentences = append(sentences, sentence)
				start = end
			}
			// If too short, leave in buffer to merge with next sentence.
		}
	}

	s.buffer = s.buffer[start:]
	return sentences
}

// isSentenceEnd checks if a rune is a sentence-ending punctuation.
func isSentenceEnd(r rune) bool {
	return r == '.' || r == '!' || r == '?' || r == '。' || r == '！' || r == '？' || r == '\n'
}
